### ISSUE TITLE
get_setting': undefined method []' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by michaelpjohnson** [sensu-plugins/sensu-plugins-slack#20]
I am getting the following stack trace in my logs when running this plugin:

```json
{
  "timestamp": "2016-06-02T13:59:19.245303+0000",
  "level": "info",
  "message": "handler output",
  "handler": {
    "type": "pipe",
    "severities": [
      "ok",
      "critical"
    ],
    "command": "handler-slack.rb",
    "webhook_url": "https://hooks.slack.com/services/<REDACTED>",
    "name": "slack"
  },
  "output": [
    "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.\n/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.\n/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.\n/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-0.1.2/bin/handler-slack.rb:82:in `get_setting': undefined method `[]' for nil:NilClass (NoMethodError)\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-0.1.2/bin/handler-slack.rb:54:in `message_template'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-0.1.2/bin/handler-slack.rb:91:in `build_description'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-0.1.2/bin/handler-slack.rb:86:in `handle'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'\n"
  ]
}
```

It looks like this is the main issue: `get_setting': undefined method []' for nil:NilClass (NoMethodError)\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-0.1.2/bin/handler-slack.rb:54`

```json
cat /etc/sensu/conf.d/handlers/slack.json
{
  "handlers": {
    "slack": {
      "type": "pipe",
      "severities": [
        "ok",
        "critical"
      ],
      "command": "handler-slack.rb",
      "webhook_url": "https://hooks.slack.com/services/<REDACTED>"
    }
  }
}
```

**Comment by bzang** [comment]
I had the same issue, it looks like you need to pass the plugin specific params as a separate param. So your slack.json file should look something like this:
```
{
  "handlers": {
    "slack": {
      "type": "pipe",
     "command": "handler-slack.rb",
      "severities": [
        "ok",
        "critical"
      ]
  },
  "slack": {
     "webhook_url": "https://hooks.slack.com/services/<REDACTED>"
  }
}
```

**Comment by michaelpjohnson** [comment]
@bzang That did the trick. I'm using Chef, so I need to find a way to override the recipe behavior. Thanks!

**Comment by rambler** [comment]
@michaelpjohnson I'm sure you've figured this out since but if anyone else finds this trying to do the same thing, it works for me with something like this:

```ruby
sensu_snippet 'slack' do
    content(webhook_url: 'https://hooks.slack.com/services/<REDACTED>',
            bot_name: 'sensu',
            channel: '#sensu-alerts')
end
```
