### ISSUE TITLE
Problem with "127" (Unknown) exit codes

### ISSUE THREAD

**Issue by xblitz** [sensu-plugins/sensu-plugins-slack#34]
it seems that Unknown (127) exit codes are not handled by the slack handler and gives this error:
```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:191:in 'fetch': key not found: 127 (KeyError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:191:in 'color'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:174:in 'payload'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:135:in 'post_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:92:in 'handle'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-handler.rb:81:in 'block in <class:Handler>'
```

**Comment by fsniper** [comment]
I get this error too. Adding a fetch default, or adding a unknown value to colors would fix that.

**Comment by majormoses** [comment]
I have proposed #62 which should resolve your problem as well as the next one you didnt even know you had. Please test it out and let me know if there is anything else that needs to be handled that I did not see based on your error message.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-slack/versions/3.1.1
