### ISSUE TITLE
Slack forces SSL/TLS for all endpoints, even http

### ISSUE THREAD

**Issue by zamedic** [sensu-plugins/sensu-plugins-slack#74]
if we use an internal slack compatible endpoint that uses http - then the line below breaks the request, since it forced the request to use https... 

https://github.com/sensu-plugins/sensu-plugins-slack/blob/6bef292b5e460b5760aa5b61e0ac446b04833e07/bin/handler-slack.rb#L150

the error we receive is 

{"timestamp":"2019-01-23T12:19:56.779398+0200","level":"error","message":"handler output","handler":{"type":"pipe","severities":["ok","warning","critical","unknown"],"command":"handler-slack.rb -j slack_chopchop","name":"slack_chopchop"},"event":{"id":"a5c5eb89-300f-4a3b-82f8-e10c54bedf4b"},"output":["/opt/sensu/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError)\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:948:in `connect'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:887:in `do_start'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:876:in `start'\n\tfrom /opt/sensu/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-slack-3.1.1/bin/handler-slack.rb:161:in `post_data'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-slack-3.1.1/bin/handler-slack.rb:113:in `handle'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.7.0/lib/sensu-handler.rb:89:in `block in <class:Handler>'\n"]}

**Comment by majormoses** [comment]
Is there some reason you can't use something like Let's Encrypt or a self signed certificate? I am hesitant to enable poor security posture.
